# site settings
title: I'm
subtitle: kooroot
email: alswo9085@gmail.com
description: Innovative Blockchain Researcher & Engineer
baseurl: # the subpath of your site, e.g. /blog
URL: "kooroot.github.io" # the base hostname & protocol for your site
author:
street_address: 
city: Seoul
state: KR
zip_code: 
country: South Korea
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/kooroot
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/kooroot
  Twitter: https://twitter.com/k00r00t
  Telegram: https://t.me/kooroot
  Linktree: https://linktr.ee/kooroot
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
